# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            # First transport for User messages
            async_users: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: users_exchange
                        type: direct
                    queues:
                        users_queue: ~

            # Second transport for Product messages
            async_products: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: products_exchange
                        type: direct
                    queues:
                        products_queue: ~

        routing:        
            'App\Message\UserMessage': async_users
            'App\Message\ProductMessage': async_products
